### PR TITLE
feat: bump bpftrace version to v0.19.1

### LINKED ISSUE #174: FindPidByPodContainer unreliable
https://github.com/iovisor/kubectl-trace/blob/7fd30079cf6e00218d78500eb41786847df37fe4/pkg/procfs/procfs.go#L59

This code makes too many assumptions about what the file paths will look like.

Actual mount results on my cluster look like `/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod30cea2cf_1b80_4807_abad_d81453e199c5.slice/crio-a8077b08a56c0c6e33d6716557d882ac940cb09475c50372e22e84c40d0733f2.scope`

Additionally,   the following agruments get passed to the job container 
`--pod-uid=30cea2cf-1b80-4807-abad-d81453e199c5
 --container-id=cri-o://a8077b08a56c0c6e33d6716557d882ac940cb09475c50372e22e84c40d0733f2
`

We need to also trim the `cri-o://` prefix.  The pod UID seems to replace `-` with `_` so that is another issue.

This project works for me: https://github.com/yahoo/kubectl-flame/blob/master/agent/utils/process.go#L35

### LINKED ISSUE #200: update bpftrace to 0.18.0
bpftrace now uses libbpf, I'm sure switching to that version will make easier to deal with the kernel headers issues many users reported.

If anyone wants to give a shot, [take a look here](https://github.com/iovisor/kubectl-trace/blob/master/Makefile#L34).

### PR DESCRIPTION
**Pull request by cakemanny**
This resolves #200 

It bumps the bptrace version to v0.19.1 .

I chose 0.19.1 as it's the most recent `quay.io/iovisor/bpftrace` tag. (It seems they are working on switching to using a Nix based build for later versions).
I wasn't able to successfully able to bump bcc.

The other changes are related to
- getting the Github Actions to run in the forked repo - i.e. `$GIT_ORG` is expanded in integration tests
- getting the integration tests to pass with more recent versions of Minikube and Kind.
   - I ended up bumping the version of go in order to be able to debug locally, so I hope it's ok that that's included also.

By all means let me know if it needs additional touches or splitting out into separate PRs.

PS: also fixes #174

### CODE REVIEW

**Comment by cakemanny** [comment]
It seems the github actions are actually failing still, I'll have to come back to this. I've put in draft mode for now.
I also tried to follow the instructions for signing the commits but for some reason they're showing as unverified so I'll have to revisit that too.

**Comment by cakemanny** [comment]
@fntlnz, would you be the one to look at this?

**Comment by fntlnz** [comment]
Thanks @cakemanny - This was long due. I'll take a look

**Comment by fntlnz** [comment]
I'm still looking into this @cakemanny - I did not forget!

**Comment by cakemanny** [comment]
Hey @fntlnz, I guess you've still not had time? Or is there something I can do to help, such as break parts out or explain better anything that looks a bit mysterious?

**Comment by fntlnz** [comment]
@cakemanny yes it's just my schedule the PR looks good to review, please hang on and thanks again for the great work.

**Review by fntlnz — APPROVED** [review]
LGTM! There are certain things that require further work like the versions you mentioned but this is good to be merged and we can add those later.

Thanks for the patience @cakemanny and for the contribution 🎉

**Pull request merged**
