### PR TITLE
feat: Migrate travis CI to github actions, fixes #105

### LINKED ISSUE #105: RFC: Github Actions?
Github actions is now available and its been enabled for the iovisor github org.

Someone with admin access to this repo can add the QUAY_TOKEN to it like what is been done with travis.

The major advantage of actions over travis that I see are:

- Travis.org seems to be getting aged-out for travis.com
- Github actions offers much more concurrency (up to 20 jobs), so we could test kubectl trace maybe against different versions of k8s, and distros?

WDYT @leodido @fntlnz

### PR DESCRIPTION
**Pull request by dalehamel**
This moves the CI and release process to github actions from Travis for #105 

To fully test this, I will need to either be made a full admin of the repo (@fntlnz @leodido are you able to do this?), or have an existing admin add the QUAY_TOKEN secret environment variable.

Here is a sample run: https://github.com/dalehamel/kubectl-trace/actions/runs/322349438

It uploads the dist folder for cross builds, as well as the linux binary that it builds as part of the test process.

I plan on testing the gorelease script when we cut 0.1.1 shortly

### CODE REVIEW

**Review by leodido — APPROVED** [review]
Very very cool!

**Review by fntlnz — APPROVED** [review]

**Comment by fntlnz** [comment]
Good job @dalehamel - this is very useful and better than what we had.

**Comment by fntlnz** [comment]
I removed Fixmie from the list of requirements for merge in Branch protection rules (that app does not exist anymore).

I wanted to add the new checks from here as required but they don't appear. I guess there's some caching and I'll check later

**Comment by fntlnz** [comment]
oh wait! The new ones are `build_and_test` prefixed.
Enabled them

image

**Comment by dalehamel** [comment]
Oh this wasn't quite ready to merge, I discovered a couple more things. I'll follow-up with another PR to correct those.

**Pull request merged**
