### PR TITLE
Reveal the error in the pod level

### PR DESCRIPTION
**Pull request by Jackyen**
- Delete the redundant code `return &target, nil`
- Reveal the error msg

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]
LGTM - thanks @Jackyen

**Comment by Jackyen** [comment]
I merged the newest change on master.
Please approve the runner again @fntlnz . 
Thanks !

**Review by leodido — APPROVED** [review]
✅ 

Approved the new run! Thank you 💯

**Comment by Jackyen** [comment]
@leodido  Is there anything wrong with the ubuntu-16.04 checks?

**Comment by fntlnz** [comment]
Did a rerun, let's see what happens !

**Comment by fntlnz** [comment]
The 16.04 environments have been removed from Github Actions, I'll merge this and remove them from main.

**Pull request merged**
